require: rubocop-rspec

HashSyntax:
  EnforcedStyle: hash_rockets

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Metrics/LineLength:
  Max: 120

# TODO: Cleanup
Metrics/ModuleLength:
  Max: 200

# TODO: Cleanup
Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 15

Style/ModuleFunction:
  Enabled: false

Metrics/AbcSize:
  Max: 20

AlignHash:
  EnforcedHashRocketStyle: table
